# 학습 관련 하이퍼파라미터
config: './config.yaml'
data: 'tiny-imagenet'
data_dir: './tiny-imagenet-200'
batch_size: 256     
epochs: 1          
lr: 0.01   

seed: 42
num_workers: 1
device: 'cuda'         
save_interval: 20    
save_path: 'save'
checkpoint: null

patch_size: 15
jitter: 3


model:
  name: resnet18  
  dim: [512, 4096]


